package loadbalancer

import (
	"errors"
	"fmt"
	"reflect"
	"slices"
	"strings"

	"github.com/UpCloudLtd/upcloud-go-api/v8/upcloud"
	"github.com/UpCloudLtd/upcloud-go-api/v8/upcloud/request"
)

var errConfigNotEqual = errors.New("load balancer configs are not equal")

func createLoadBalancerRequestsEqual(r1, r2 *request.CreateLoadBalancerRequest) error {
	if r1.Name != r2.Name {
		return fieldValueNotEqualError("name")
	}
	if r1.Plan != r2.Plan {
		return fieldValueNotEqualError("plan")
	}
	if r1.Zone != r2.Zone {
		return fieldValueNotEqualError("zone")
	}
	if r1.NetworkUUID != r2.NetworkUUID {
		return fieldValueNotEqualError("network UUID")
	}
	if r1.ConfiguredStatus != r2.ConfiguredStatus {
		return fieldValueNotEqualError("configured status")
	}
	// Maintenance DOW and maintenance time are optional fields and values are autogenerated by the backend if not provided.
	// Compare these fields only if they are defined.
	if r1.MaintenanceDOW != "" && r2.MaintenanceDOW != "" && r1.MaintenanceDOW != r2.MaintenanceDOW {
		return fieldValueNotEqualError("maintenance DOW")
	}
	if r1.MaintenanceTime != "" && r2.MaintenanceTime != "" && r1.MaintenanceTime != r2.MaintenanceTime {
		return fieldValueNotEqualError("maintenance time")
	}

	if len(r1.Networks) != len(r2.Networks) {
		return lengthNotEqualError("network")
	}
	if len(r1.Resolvers) != len(r2.Resolvers) {
		return lengthNotEqualError("resolvers")
	}
	if len(r1.Labels) != len(r2.Labels) {
		return lengthNotEqualError("labels")
	}
	if len(r1.Frontends) != len(r2.Frontends) {
		return lengthNotEqualError("frontends")
	}
	if len(r1.Backends) != len(r2.Backends) {
		return lengthNotEqualError("backends")
	}

	sortCreateLoadBalancerRequestSlices(r1)
	sortCreateLoadBalancerRequestSlices(r2)

	if !reflect.DeepEqual(r1.Networks, r2.Networks) {
		return fieldValueNotEqualError("networks")
	}
	if !reflect.DeepEqual(r1.Resolvers, r2.Resolvers) {
		return fieldValueNotEqualError("resolvers")
	}
	if !reflect.DeepEqual(r1.Labels, r2.Labels) {
		return fieldValueNotEqualError("labels")
	}
	if !reflect.DeepEqual(r1.Frontends, r2.Frontends) {
		return fieldValueNotEqualError("frontends")
	}
	if !reflect.DeepEqual(r1.Backends, r2.Backends) {
		return fieldValueNotEqualError("backends")
	}

	return nil
}

func sortCreateLoadBalancerRequestSlices(r *request.CreateLoadBalancerRequest) {
	slices.SortStableFunc(r.Networks, func(a, b request.LoadBalancerNetwork) int {
		return strings.Compare(a.Name, b.Name)
	})
	slices.SortStableFunc(r.Resolvers, func(a, b request.LoadBalancerResolver) int {
		return strings.Compare(a.Name, b.Name)
	})
	slices.SortStableFunc(r.Labels, func(a, b upcloud.Label) int {
		return strings.Compare(a.Key, b.Key)
	})
	for i := range r.Backends {
		slices.SortFunc(r.Backends[i].Members, func(a, b request.LoadBalancerBackendMember) int {
			return strings.Compare(a.Name, b.Name)
		})
		slices.SortFunc(r.Backends[i].TLSConfigs, func(a, b request.LoadBalancerBackendTLSConfig) int {
			return strings.Compare(a.Name, b.Name)
		})
	}
	for i := range r.Frontends {
		slices.SortFunc(r.Frontends[i].Rules, func(a, b request.LoadBalancerFrontendRule) int {
			return strings.Compare(a.Name, b.Name)
		})
		for y := range r.Frontends[i].Rules {
			// TODO: We should probably improve these rule sort functions at some point.
			slices.SortStableFunc(r.Frontends[i].Rules[y].Actions, func(a, b upcloud.LoadBalancerAction) int {
				return strings.Compare(string(a.Type), string(b.Type))
			})
			slices.SortStableFunc(r.Frontends[i].Rules[y].Matchers, func(a, b upcloud.LoadBalancerMatcher) int {
				return strings.Compare(string(a.Type), string(b.Type))
			})
		}
		slices.SortFunc(r.Frontends[i].TLSConfigs, func(a, b request.LoadBalancerFrontendTLSConfig) int {
			return strings.Compare(a.Name, b.Name)
		})
		slices.SortFunc(r.Frontends[i].Networks, func(a, b upcloud.LoadBalancerFrontendNetwork) int {
			return strings.Compare(a.Name, b.Name)
		})
	}
	slices.SortFunc(r.Frontends, func(a, b request.LoadBalancerFrontend) int {
		return strings.Compare(a.Name, b.Name)
	})
	slices.SortFunc(r.Backends, func(a, b request.LoadBalancerBackend) int {
		return strings.Compare(a.Name, b.Name)
	})
}

func lengthNotEqualError(field string) error {
	return fmt.Errorf("length of %s fields is not the same; %w", field, errConfigNotEqual)
}

func fieldValueNotEqualError(field string) error {
	return fmt.Errorf("%s fields differ; %w", field, errConfigNotEqual)
}
